#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Code desktop='^3' follow=on
bspc rule -a smplayer desktop='^4' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#Launch polybar
sh ~/.config/polybar/runbar.sh &

#Picom 
picom -f &

#Restore Wallpaper
nitrogen --restore &

#notification 
dunst
